-- Borrar base de datos
DROP DATABASE IF EXISTS dbDIAGRAMA;

-- Crear base de datos
CREATE DATABASE dbDIAGRAMA;

-- Usar base de datos
USE dbDIAGRAMA;

-- Crear tabla persona
CREATE TABLE PERSONA(
	DNIPER		CHAR(8),
    NOMPER		VARCHAR(50),
    APEPER		VARCHAR(50),
    FECNACPER	DATE,
    CELPER		VARCHAR(9),
    EMAPER		VARCHAR(100),
    SEXPER		CHAR(1),
    TIPPER		CHAR(3),
    DISTPER		VARCHAR(80),
    FECREGPER	TIMESTAMP,
    PWSPER		VARCHAR(20),
    CONSTRAINT DNIPER PRIMARY KEY(DNIPER)
);

-- Crear tabla histórico
CREATE TABLE HISTORICO(
	IDHIS		INT,
    DNIPER		CHAR(8),
    FECFINHIST	DATE,
    TIPHIS		CHAR(3),
    COMEHIST	VARCHAR(100),
    CONSTRAINT IDHIS PRIMARY KEY (IDHIS)
);

-- Crear tabla departamento
CREATE TABLE DEPARTAMENTO(
	IDDEP		INT,
    NOMDEP		VARCHAR(50),
    DNIPER		CHAR(8),
    SALJEFDEP	DECIMAL(8,2),
    CONSTRAINT IDDEP PRIMARY KEY (IDDEP)
);

-- Crear tabla empleado
CREATE TABLE EMPLEADO(
	IDEMP		INT,
    DNIPER		CHAR(8),
    FECINGEMP	DATE,
    CARGEMP		VARCHAR(40),
    SALEMP		DECIMAL(6,2),
    IDDEP		INT,
    ESTEMP		CHAR(1),
    CONSTRAINT IDEMP PRIMARY KEY (IDEMP)
);

-- Crear tabla inscripción
CREATE TABLE INSCRIPCION(
	IDINSC		INT,
    DNIPER		CHAR(8),
    IDEMP		INT,
    IDOFER		INT,
    FECINS		DATE,
    EVALINSC		INT,
    CONSTRAINT IDINSC PRIMARY KEY (IDINSC)
);

-- Crear tabla oferta
CREATE TABLE OFERTA(
	IDOFER		INT,
    CODCUR		CHAR(3),
    FECOFER		DATE,
    FECINICCUROFER	DATE,
    IDEMP		INT,
    CONSTRAINT IDOFER PRIMARY KEY (IDOFER)
);

-- Crear tabla curso
CREATE TABLE CURSO(
	CODCUR		CHAR(3),
    DESCUR		VARCHAR(30),
    CATCUR		CHAR(3),
    DURCUR		INT,
    CONSTRAINT CODCUR PRIMARY KEY (CODCUR)
);

-- Crear relación entre tablas

-- Relación entre las tablas HISTORICO - PERSONA
ALTER TABLE HISTORICO ADD CONSTRAINT historico_persona_DNIPER FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relación entre las tablas DEPARTAMENTO - PERSONA
ALTER TABLE DEPARTAMENTO ADD CONSTRAINT departamento_persona_DNIPER FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relación entre las tablas EMPLEADO - DEPARTAMENTO
ALTER TABLE EMPLEADO ADD CONSTRAINT empleado_departamento_IDDEP FOREIGN KEY (IDDEP) REFERENCES DEPARTAMENTO (IDDEP);

-- Relación entre las tablas EMPLEADO - PERSONA
ALTER TABLE EMPLEADO ADD CONSTRAINT empleado_persona_IDDEP FOREIGN KEY (IDDEP) REFERENCES DEPARTAMENTO (IDDEP);

-- Relación entre las tablas INSCRIPCIÓN - PERSONA
ALTER TABLE INSCRIPCION ADD CONSTRAINT inscripcion_persona_DNIPER FOREIGN KEY (DNIPER) REFERENCES PERSONA (DNIPER);

-- Relación entre las tablas INSCRIPCIÓN - EMPLEADO
ALTER TABLE INSCRIPCION ADD CONSTRAINT inscripcion_empleado_IDEMP FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relación entre las tablas INSCRIPCIÓN - OFERTA
ALTER TABLE INSCRIPCION ADD CONSTRAINT inscripcion_oferta_IDOFER FOREIGN KEY (IDOFER) REFERENCES OFERTA (IDOFER);

-- Relación entre las tablas OFERTA - EMPLEADO
ALTER TABLE OFERTA ADD CONSTRAINT oferta_empleado_IDEMP FOREIGN KEY (IDEMP) REFERENCES EMPLEADO (IDEMP);

-- Relación entre las tablas OFERTA - CURSO
ALTER TABLE OFERTA ADD CONSTRAINT oferta_curso_CODCUR FOREIGN KEY (CODCUR) REFERENCES CURSO (CODCUR);